-- 유저 시퀀스
DROP SEQUENCE USER_SEQ;

-- 제품 시퀀스
DROP SEQUENCE PRODUCT_SEQ;

-- 판매 시퀀스
DROP SEQUENCE SELL_SEQ;

-- 장바구니 시퀀스
DROP SEQUENCE CART_SEQ;

-- 행사 시퀀스
DROP SEQUENCE EVENT_SEQ;

-- 예약 시퀀스
DROP SEQUENCE RESERVE_SEQ;

-- 고객센터 시퀀스
DROP SEQUENCE SERVICE_SEQ;

-- 게시글 시퀀스
DROP SEQUENCE BOARD_SEQ;

DROP TABLE TB_COM_CODE CASCADE CONSTRAINT;

--회원정보
DROP TABLE TB_COM_USER CASCADE CONSTRAINT;

--제품정보
DROP TABLE TB_PRODUCT CASCADE CONSTRAINT;

--제품댓글정보
DROP TABLE TB_PRODUCT_REPLY CASCADE CONSTRAINT;

--제품별점정보

--판매내역정보
DROP TABLE TB_SELL CASCADE CONSTRAINT;

--장바구니정보
DROP TABLE TB_CART CASCADE CONSTRAINT;

--행사정보
DROP TABLE TB_EVENT CASCADE CONSTRAINT;

--예약정보
DROP TABLE TB_RESERVE CASCADE CONSTRAINT;

--행사댓글정보
DROP TABLE TB_EVENT_REPLY CASCADE CONSTRAINT;

--행사별점정보
DROP TABLE TB_EVENT_MARK CASCADE CONSTRAINT;

-- 고객센터정보
DROP TABLE TB_SERVICE CASCADE CONSTRAINT;

--게시판정보
DROP TABLE TB_BOARD CASCADE CONSTRAINT;

--댓글정보
DROP TABLE TB_REPLY CASCADE CONSTRAINT;

-- 공감도정보
DROP TABLE TB_MARK CASCADE CONSTRAINT;

commit;
